server:
  port: 8001
spring:
  cloud:
    config:
      server:
        git:
          default-label: oauth-server
          uri: https://github.com/RicharLeon/MICROSERVICIOS-CLINICADELPIE
          search-paths: config-data
          username: RicharLeon
          password: 
  application:
    name: config-services